#!/bin/bash
./kudu-master --never_fsync=true --local_ip_for_outbound_sockets=127.0.0.1 --raft_heartbeat_interval_ms=200 --fs_data_dirs=$PWD/../kuduWorkingDir/data/master --fs_wal_dir=$PWD/../kuduWorkingDir/wal/master --rpc_bind_addresses=127.0.0.1:64046 --webserver_interface=127.0.0.1 --never_fsync=true --heap_profile_path=$PWD/../kuduWorkingDir/kudu_master_heap --unlock_experimental_flags=true --unlock_unsafe_flags=true --local_ip_for_outbound_sockets=127.0.0.1 --flagfile=$PWD/kudu-master.flags --webserver_doc_root=$PWD/www --logtostderr=true &
./kudu-tserver --never_fsync=true --flush_threshold_mb=1 --local_ip_for_outbound_sockets=127.0.0.1 --fs_data_dirs=$PWD/../kuduWorkingDir/data/ts-0 --fs_wal_dir=$PWD/../kuduWorkingDir/wal/ts-0 --rpc_bind_addresses=127.0.0.1:64052 --webserver_interface=127.0.0.1 --webserver_port=64053 --flush_threshold_mb=1 --tserver_master_addrs=127.0.0.1:64046 --never_fsync=true --heap_profile_path=$PWD/ts0_heap --unlock_experimental_flags=true --unlock_unsafe_flags=true --local_ip_for_outbound_sockets=127.0.0.1 --flagfile=kudu-master.flags --webserver_doc_root=$PWD/www --logtostderr=true &
./kudu-tserver --never_fsync=true --flush_threshold_mb=1 --local_ip_for_outbound_sockets=127.0.0.1 --fs_data_dirs=$PWD/../kuduWorkingDir/data/ts-1 --fs_wal_dir=$PWD/../kuduWorkingDir/wal/ts-1 --rpc_bind_addresses=127.0.0.1:64050 --webserver_interface=127.0.0.1 --webserver_port=64051 --flush_threshold_mb=1 --tserver_master_addrs=127.0.0.1:64046 --never_fsync=true --heap_profile_path=$PWD/ts1_heap --unlock_experimental_flags=true --unlock_unsafe_flags=true --local_ip_for_outbound_sockets=127.0.0.1 --flagfile=kudu-master.flags --webserver_doc_root=$PWD/www --logtostderr=true &
./kudu-tserver --never_fsync=true --flush_threshold_mb=1 --local_ip_for_outbound_sockets=127.0.0.1 --fs_data_dirs=$PWD/../kuduWorkingDir/data/ts-2 --fs_wal_dir=$PWD/../kuduWorkingDir/wal/ts-2 --rpc_bind_addresses=127.0.0.1:64048 --webserver_interface=127.0.0.1 --webserver_port=64049 --flush_threshold_mb=1 --tserver_master_addrs=127.0.0.1:64046 --never_fsync=true --heap_profile_path=$PWD/ts2_heap --unlock_experimental_flags=true --unlock_unsafe_flags=true --local_ip_for_outbound_sockets=127.0.0.1 --flagfile=kudu-master.flags --webserver_doc_root=$PWD/www --logtostderr=true &




